package net.kdt.pojavlaunch

@Suppress("unused")
object LwjglGlfwKeycode {
    const val GLFW_KEY_UNKNOWN: Int = 0

    const val GLFW_KEY_SPACE: Int = 32
    const val GLFW_KEY_APOSTROPHE: Int = 39
    const val GLFW_KEY_COMMA: Int = 44
    const val GLFW_KEY_MINUS: Int = 45
    const val GLFW_KEY_PERIOD: Int = 46
    const val GLFW_KEY_SLASH: Int = 47
    const val GLFW_KEY_0: Int = 48
    const val GLFW_KEY_1: Int = 49
    const val GLFW_KEY_2: Int = 50
    const val GLFW_KEY_3: Int = 51
    const val GLFW_KEY_4: Int = 52
    const val GLFW_KEY_5: Int = 53
    const val GLFW_KEY_6: Int = 54
    const val GLFW_KEY_7: Int = 55
    const val GLFW_KEY_8: Int = 56
    const val GLFW_KEY_9: Int = 57
    const val GLFW_KEY_SEMICOLON: Int = 59
    const val GLFW_KEY_EQUAL: Int = 61
    const val GLFW_KEY_A: Int = 65
    const val GLFW_KEY_B: Int = 66
    const val GLFW_KEY_C: Int = 67
    const val GLFW_KEY_D: Int = 68
    const val GLFW_KEY_E: Int = 69
    const val GLFW_KEY_F: Int = 70
    const val GLFW_KEY_G: Int = 71
    const val GLFW_KEY_H: Int = 72
    const val GLFW_KEY_I: Int = 73
    const val GLFW_KEY_J: Int = 74
    const val GLFW_KEY_K: Int = 75
    const val GLFW_KEY_L: Int = 76
    const val GLFW_KEY_M: Int = 77
    const val GLFW_KEY_N: Int = 78
    const val GLFW_KEY_O: Int = 79
    const val GLFW_KEY_P: Int = 80
    const val GLFW_KEY_Q: Int = 81
    const val GLFW_KEY_R: Int = 82
    const val GLFW_KEY_S: Int = 83
    const val GLFW_KEY_T: Int = 84
    const val GLFW_KEY_U: Int = 85
    const val GLFW_KEY_V: Int = 86
    const val GLFW_KEY_W: Int = 87
    const val GLFW_KEY_X: Int = 88
    const val GLFW_KEY_Y: Int = 89
    const val GLFW_KEY_Z: Int = 90
    const val GLFW_KEY_LEFT_BRACKET: Int = 91
    const val GLFW_KEY_BACKSLASH: Int = 92
    const val GLFW_KEY_RIGHT_BRACKET: Int = 93
    const val GLFW_KEY_GRAVE_ACCENT: Int = 96
    const val GLFW_KEY_WORLD_1: Int = 161
    const val GLFW_KEY_WORLD_2: Int = 162

    const val GLFW_KEY_ESCAPE: Int = 256
    const val GLFW_KEY_ENTER: Int = 257
    const val GLFW_KEY_TAB: Int = 258
    const val GLFW_KEY_BACKSPACE: Int = 259
    const val GLFW_KEY_INSERT: Int = 260
    const val GLFW_KEY_DELETE: Int = 261
    const val GLFW_KEY_RIGHT: Int = 262
    const val GLFW_KEY_LEFT: Int = 263
    const val GLFW_KEY_DOWN: Int = 264
    const val GLFW_KEY_UP: Int = 265
    const val GLFW_KEY_PAGE_UP: Int = 266
    const val GLFW_KEY_PAGE_DOWN: Int = 267
    const val GLFW_KEY_HOME: Int = 268
    const val GLFW_KEY_END: Int = 269
    const val GLFW_KEY_CAPS_LOCK: Int = 280
    const val GLFW_KEY_SCROLL_LOCK: Int = 281
    const val GLFW_KEY_NUM_LOCK: Int = 282
    const val GLFW_KEY_PRINT_SCREEN: Int = 283
    const val GLFW_KEY_PAUSE: Int = 284
    const val GLFW_KEY_F1: Int = 290
    const val GLFW_KEY_F2: Int = 291
    const val GLFW_KEY_F3: Int = 292
    const val GLFW_KEY_F4: Int = 293
    const val GLFW_KEY_F5: Int = 294
    const val GLFW_KEY_F6: Int = 295
    const val GLFW_KEY_F7: Int = 296
    const val GLFW_KEY_F8: Int = 297
    const val GLFW_KEY_F9: Int = 298
    const val GLFW_KEY_F10: Int = 299
    const val GLFW_KEY_F11: Int = 300
    const val GLFW_KEY_F12: Int = 301
    const val GLFW_KEY_F13: Int = 302
    const val GLFW_KEY_F14: Int = 303
    const val GLFW_KEY_F15: Int = 304
    const val GLFW_KEY_F16: Int = 305
    const val GLFW_KEY_F17: Int = 306
    const val GLFW_KEY_F18: Int = 307
    const val GLFW_KEY_F19: Int = 308
    const val GLFW_KEY_F20: Int = 309
    const val GLFW_KEY_F21: Int = 310
    const val GLFW_KEY_F22: Int = 311
    const val GLFW_KEY_F23: Int = 312
    const val GLFW_KEY_F24: Int = 313
    const val GLFW_KEY_F25: Int = 314
    const val GLFW_KEY_KP_0: Int = 320
    const val GLFW_KEY_KP_1: Int = 321
    const val GLFW_KEY_KP_2: Int = 322
    const val GLFW_KEY_KP_3: Int = 323
    const val GLFW_KEY_KP_4: Int = 324
    const val GLFW_KEY_KP_5: Int = 325
    const val GLFW_KEY_KP_6: Int = 326
    const val GLFW_KEY_KP_7: Int = 327
    const val GLFW_KEY_KP_8: Int = 328
    const val GLFW_KEY_KP_9: Int = 329
    const val GLFW_KEY_KP_DECIMAL: Int = 330
    const val GLFW_KEY_KP_DIVIDE: Int = 331
    const val GLFW_KEY_KP_MULTIPLY: Int = 332
    const val GLFW_KEY_KP_SUBTRACT: Int = 333
    const val GLFW_KEY_KP_ADD: Int = 334
    const val GLFW_KEY_KP_ENTER: Int = 335
    const val GLFW_KEY_KP_EQUAL: Int = 336
    const val GLFW_KEY_LEFT_SHIFT: Int = 340
    const val GLFW_KEY_LEFT_CONTROL: Int = 341
    const val GLFW_KEY_LEFT_ALT: Int = 342
    const val GLFW_KEY_LEFT_SUPER: Int = 343
    const val GLFW_KEY_RIGHT_SHIFT: Int = 344
    const val GLFW_KEY_RIGHT_CONTROL: Int = 345
    const val GLFW_KEY_RIGHT_ALT: Int = 346
    const val GLFW_KEY_RIGHT_SUPER: Int = 347
    const val GLFW_KEY_MENU: Int = 348
    const val GLFW_KEY_LAST: Int = GLFW_KEY_MENU

    const val GLFW_MOD_SHIFT = 0x1
    const val GLFW_MOD_CONTROL = 0x2
    const val GLFW_MOD_ALT = 0x4
    const val GLFW_MOD_SUPER = 0x8
    const val GLFW_MOD_CAPS_LOCK = 0x10
    const val GLFW_MOD_NUM_LOCK = 0x20

    const val GLFW_MOUSE_BUTTON_1: Int = 0
    const val GLFW_MOUSE_BUTTON_2: Int = 1
    const val GLFW_MOUSE_BUTTON_3: Int = 2
    const val GLFW_MOUSE_BUTTON_4: Int = 3
    const val GLFW_MOUSE_BUTTON_5: Int = 4
    const val GLFW_MOUSE_BUTTON_6: Int = 5
    const val GLFW_MOUSE_BUTTON_7: Int = 6
    const val GLFW_MOUSE_BUTTON_8: Int = 7
    const val GLFW_MOUSE_BUTTON_LAST: Int = GLFW_MOUSE_BUTTON_8
    const val GLFW_MOUSE_BUTTON_LEFT: Int = GLFW_MOUSE_BUTTON_1
    const val GLFW_MOUSE_BUTTON_RIGHT: Int = GLFW_MOUSE_BUTTON_2
    const val GLFW_MOUSE_BUTTON_MIDDLE: Int = GLFW_MOUSE_BUTTON_3

    const val GLFW_VISIBLE = 0x20004
    const val GLFW_HOVERED = 0x2000B
}
