apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation 'org.json:json:20230618'
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    manifest {
        attributes("Manifest-Version": "1.0",
                "PreMain-Class": "git.artdeell.installer_agent.Agent")
    }
}
